google.oauth.credentials.path=/client_secret_private.json
google.service-account.credentials.path=/cashflow-438618-42013d3be78c.json
google.auth.request.initializer=service-account

spring.datasource.url=jdbc:postgresql://localhost:5432/cashflow
spring.datasource.username=cashflow
spring.datasource.password=cashflow
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.hbm2ddl.auto=none

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

spring.web.error.include-message=always
server.port=8000